### ISSUE TITLE
look at distinct function

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/wgsaparsr#73]
perhaps distinct should use the '|' character as a field separator, too (`Ensembl_Regulatory_Build_TFBS` wouldn't really need a pivot char then)

**Comment by jaind** [comment]
.parseDistinct()  returns a `|`-separated string and hence fields processed by  .parseDistinct() are then pivoted by `|`.  The function doe snot need to change until we decide to extract distinct values  from a field that has  `|`  as a inbuilt separator.  For now .parseDistinct() needs no edits.
